<?php

namespace JJ\WeddingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrantRepository extends EntityRepository
{
}
