<?php

namespace JJ\WeddingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RsvpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RsvpRepository extends EntityRepository
{
}
